/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.bioscomputacion.Formularios;

import ar.com.bioscomputacion.Funciones.ConexionBD;
import ar.com.bioscomputacion.Funciones.StockRealMiel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Caco
 */
public class FrmGestionStockMiel extends javax.swing.JInternalFrame {

    ConexionBD mysql = new ConexionBD();
    Connection cn = mysql.getConexionBD();
    
    /**
     * Creates new form FrmGenerico
     */
    public FrmGestionStockMiel() throws SQLException {
        initComponents();
        inicializar();
        obtenerNombreLocacion();
        obtenerDetalleStock();
    }

    public void inicializar(){
        
        lLocacion0.setText("");
        lCantidadMielLocacion0.setText("");
        lLocacion1.setText("");
        lCantidadMielLocacion1.setText("");
        lLocacion2.setText("");
        lCantidadMielLocacion2.setText("");
        lTotalMielDeposito.setText("");
        lTotalMielDeposito.setText("");
        
        
    }
    
        public void obtenerNombreLocacion() throws SQLException{
        
        //deberia obtener el numero total de locaciones cargadas en el sistema
        //para poder saber cuantas iteraciones realizar
        DefaultTableModel modelo; 
        
        Statement st = cn.createStatement();

        //por ahora asumo que son 3 las locaciones cargadas
        StockRealMiel stock = new StockRealMiel();
        
        //locacion 0
        lLocacion0.setText(stock.obtenerNombreLocacion(0));
        
        //locacion 1
        lLocacion1.setText(stock.obtenerNombreLocacion(1));
        
        //locacion 2
        lLocacion2.setText(stock.obtenerNombreLocacion(2));
        
    }

    public void obtenerDetalleStock() throws SQLException{
        
        //deberia obtener el numero total de locaciones cargadas en el sistema
        //para poder saber cuantas iteraciones realizar
        DefaultTableModel modelo; 
        
        Statement st = cn.createStatement();

        //por ahora asumo que son 3 las locaciones cargadas
        StockRealMiel stock = new StockRealMiel();
        
        //locacion 0
        lCantidadMielLocacion0.setText(stock.obtenerDetalleStockLocacion(0));
        
        //locacion 1
        lCantidadMielLocacion1.setText(stock.obtenerDetalleStockLocacion(1));
        
        //locacion 2
        lCantidadMielLocacion2.setText(stock.obtenerDetalleStockLocacion(2));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbPagoTotal = new javax.swing.JLabel();
        lCantidadMielLocacion0 = new javax.swing.JLabel();
        lbPagoTotal2 = new javax.swing.JLabel();
        lTotalMielDeposito = new javax.swing.JLabel();
        lLocacion0 = new javax.swing.JLabel();
        lbPagoTotal1 = new javax.swing.JLabel();
        lLocacion1 = new javax.swing.JLabel();
        lCantidadMielLocacion1 = new javax.swing.JLabel();
        lbPagoTotal3 = new javax.swing.JLabel();
        lLocacion2 = new javax.swing.JLabel();
        lCantidadMielLocacion2 = new javax.swing.JLabel();
        rsbrSalir = new rojeru_san.RSButtonRiple();

        setTitle("GESTION DE STOCK DE MIEL - CAM HONEY BROTHERS");

        jPanel1.setBackground(new java.awt.Color(51, 84, 111));

        rSPanelShadow2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("STOCK REAL DE MIEL DE LA EMPRESA");

        lbPagoTotal.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lbPagoTotal.setForeground(new java.awt.Color(153, 255, 255));
        lbPagoTotal.setText("KGS. ACOPIADOS EN:");

        lCantidadMielLocacion0.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lCantidadMielLocacion0.setForeground(new java.awt.Color(153, 255, 255));
        lCantidadMielLocacion0.setText("0.00");

        lbPagoTotal2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lbPagoTotal2.setForeground(new java.awt.Color(255, 255, 102));
        lbPagoTotal2.setText("MIEL EN DEPOSITO/S:");

        lTotalMielDeposito.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lTotalMielDeposito.setForeground(new java.awt.Color(255, 255, 102));
        lTotalMielDeposito.setText("0.00");

        lLocacion0.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lLocacion0.setForeground(new java.awt.Color(153, 255, 255));
        lLocacion0.setText("KGS. ACOPIADOS EN:");

        lbPagoTotal1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lbPagoTotal1.setForeground(new java.awt.Color(204, 204, 255));
        lbPagoTotal1.setText("KGS. ACOPIADOS EN:");

        lLocacion1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lLocacion1.setForeground(new java.awt.Color(204, 204, 255));
        lLocacion1.setText("KGS. ACOPIADOS EN:");

        lCantidadMielLocacion1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lCantidadMielLocacion1.setForeground(new java.awt.Color(204, 204, 255));
        lCantidadMielLocacion1.setText("0.00");

        lbPagoTotal3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lbPagoTotal3.setForeground(new java.awt.Color(255, 153, 255));
        lbPagoTotal3.setText("KGS. ACOPIADOS EN:");

        lLocacion2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lLocacion2.setForeground(new java.awt.Color(255, 153, 255));
        lLocacion2.setText("KGS. ACOPIADOS EN:");

        lCantidadMielLocacion2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lCantidadMielLocacion2.setForeground(new java.awt.Color(255, 153, 255));
        lCantidadMielLocacion2.setText("0.00");

        rsbrSalir.setBackground(new java.awt.Color(47, 110, 164));
        rsbrSalir.setText("SALIR");
        rsbrSalir.setFont(new java.awt.Font("Roboto Bold", 3, 14)); // NOI18N
        rsbrSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsbrSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelShadow2Layout = new javax.swing.GroupLayout(rSPanelShadow2);
        rSPanelShadow2.setLayout(rSPanelShadow2Layout);
        rSPanelShadow2Layout.setHorizontalGroup(
            rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                        .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                                        .addComponent(lbPagoTotal)
                                        .addGap(18, 18, 18)
                                        .addComponent(lLocacion0))
                                    .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                                        .addComponent(lbPagoTotal1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lLocacion1))
                                    .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                                        .addComponent(lbPagoTotal3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lLocacion2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelShadow2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbPagoTotal2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCantidadMielLocacion0, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCantidadMielLocacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCantidadMielLocacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTotalMielDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelShadow2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rsbrSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rSPanelShadow2Layout.setVerticalGroup(
            rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPagoTotal)
                    .addComponent(lCantidadMielLocacion0)
                    .addComponent(lLocacion0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPagoTotal1)
                    .addComponent(lCantidadMielLocacion1)
                    .addComponent(lLocacion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPagoTotal3)
                    .addComponent(lCantidadMielLocacion2)
                    .addComponent(lLocacion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPagoTotal2)
                    .addComponent(lTotalMielDeposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(rsbrSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rsbrSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsbrSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_rsbrSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lCantidadMielLocacion0;
    private javax.swing.JLabel lCantidadMielLocacion1;
    private javax.swing.JLabel lCantidadMielLocacion2;
    private javax.swing.JLabel lLocacion0;
    private javax.swing.JLabel lLocacion1;
    private javax.swing.JLabel lLocacion2;
    private javax.swing.JLabel lTotalMielDeposito;
    private javax.swing.JLabel lbPagoTotal;
    private javax.swing.JLabel lbPagoTotal1;
    private javax.swing.JLabel lbPagoTotal2;
    private javax.swing.JLabel lbPagoTotal3;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSButtonRiple rsbrSalir;
    // End of variables declaration//GEN-END:variables
}
