/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.bioscomputacion.Formularios;

import ar.com.bioscomputacion.Funciones.Planilla;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class FrmPlanillaDeControlNuevoMovimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPlanillaDeControlNuevoMovimiento
     */
    public FrmPlanillaDeControlNuevoMovimiento() {
        initComponents();
        txtNombrepersona.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JcbMovimiento = new javax.swing.JComboBox<>();
        txtMonto = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        jCbRubro = new javax.swing.JComboBox<>();
        jCbTipoMoneda = new javax.swing.JComboBox<>();
        txtNombrepersona = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();

        jPanel1.setBackground(new java.awt.Color(51, 84, 111));

        rSPanelShadow1.setBackground(new java.awt.Color(51, 84, 111));
        rSPanelShadow1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLANILLA DE CONTROL - NUEVO MOVIMIENTO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rubro:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Observaciones:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de moneda:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de movimiento:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Monto:");

        JcbMovimiento.setBackground(new java.awt.Color(51, 84, 111));
        JcbMovimiento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JcbMovimiento.setForeground(new java.awt.Color(255, 255, 255));
        JcbMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "INGRESO", "EGRESO" }));
        JcbMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbMovimientoActionPerformed(evt);
            }
        });

        txtMonto.setBackground(new java.awt.Color(51, 84, 111));
        txtMonto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(153, 255, 0));
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoKeyReleased(evt);
            }
        });

        txtObservaciones.setBackground(new java.awt.Color(51, 84, 111));
        txtObservaciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(255, 255, 255));

        jCbRubro.setBackground(new java.awt.Color(51, 84, 111));
        jCbRubro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCbRubro.setForeground(new java.awt.Color(255, 255, 255));
        jCbRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbRubroActionPerformed(evt);
            }
        });

        jCbTipoMoneda.setBackground(new java.awt.Color(51, 84, 111));
        jCbTipoMoneda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCbTipoMoneda.setForeground(new java.awt.Color(255, 255, 255));
        jCbTipoMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "EFECTIVO", "TARJ. CREDITO", "TARJ. DEBITO" }));
        jCbTipoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTipoMonedaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setText("$");

        rSButtonRiple1.setBackground(new java.awt.Color(47, 110, 164));
        rSButtonRiple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/Iconos/nuevo.png"))); // NOI18N
        rSButtonRiple1.setText("INSERTAR MOVIMIENTO");
        rSButtonRiple1.setFont(new java.awt.Font("Roboto Bold", 3, 14)); // NOI18N
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelShadow1Layout = new javax.swing.GroupLayout(rSPanelShadow1);
        rSPanelShadow1.setLayout(rSPanelShadow1Layout);
        rSPanelShadow1Layout.setHorizontalGroup(
            rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                        .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                                        .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18))
                                    .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(4, 4, 4)))
                                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JcbMovimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtObservaciones)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCbRubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCbTipoMoneda, 0, 230, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelShadow1Layout.createSequentialGroup()
                        .addComponent(rSButtonRiple1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombrepersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
                .addContainerGap())
        );
        rSPanelShadow1Layout.setVerticalGroup(
            rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JcbMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCbTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombrepersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbMovimientoActionPerformed
        String ingresos[] = new String[]{"COBRO DEUDA", "REPARACION", "ENTRADA A CAJA", "LIQUIDACION GIRE", "LIQUIDACION POSNET", "VENTA", "PLUS TURNO MAÑANA", "PLUS TURNO TARDE", "OTROS"};
        String egresos[] = new String[]{"ABONO MENSUAL POSNET", "ADELANTOS", "GTS. BIOS", "IMPUESTOS", "SUELDOS", "PROVEEDORES", "SALIDA DE CAJA", "OTROS"};

        String seleccion = JcbMovimiento.getSelectedItem().toString();

        if (seleccion == "INGRESO") {
            jCbRubro.setEnabled(true);
            jCbRubro.removeAllItems();
            for (String ingreso : ingresos) {
                jCbRubro.addItem(ingreso);
            }
        }

        if (seleccion == "EGRESO") {
            jCbRubro.setEnabled(true);
            jCbRubro.removeAllItems();
            for (String egreso : egresos) {
                jCbRubro.addItem(egreso);
            }
        }

        if (seleccion == "SELECCIONE") {
            jCbRubro.setEnabled(false);
            jCbRubro.removeAllItems();
        }
    }//GEN-LAST:event_JcbMovimientoActionPerformed

    private void jCbRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbRubroActionPerformed

    private void jCbTipoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTipoMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTipoMonedaActionPerformed

    private void txtMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyReleased
        
    }//GEN-LAST:event_txtMontoKeyReleased

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
        simbolos.setDecimalSeparator('.');
        DecimalFormat formateador = new DecimalFormat("0.00", simbolos);
        Double monto = Double.valueOf(txtMonto.getText());
        txtMonto.setText(formateador.format(monto));
    }//GEN-LAST:event_txtMontoActionPerformed

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
        java.util.Date dt = new java.util.Date();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String currentTime = sdf.format(dt);
        Planilla planilla;
        if(JcbMovimiento.getSelectedItem().equals("INGRESO")){
            planilla = new Planilla(txtNombrepersona.getText(), Timestamp.valueOf(currentTime), jCbRubro.getSelectedItem().toString(), txtObservaciones.getText(), jCbTipoMoneda.getSelectedItem().toString(), Double.valueOf(txtMonto.getText()), 0.00);
            if(planilla.insertar(planilla)){
                JOptionPane.showMessageDialog(null, "Movimiento dado de alta satisfactoriamente");
                this.dispose();
                FrmPlanillaDeControlDiaria.btnActualizar.doClick();
            }
            else{
                JOptionPane.showMessageDialog(null, "Ocurrió un error al agrega movimiento");
                this.dispose();
                FrmPlanillaDeControlDiaria.btnActualizar.doClick();
            }
        }
        else if(JcbMovimiento.getSelectedItem().equals("EGRESO")){
            planilla = new Planilla(txtNombrepersona.getText(), Timestamp.valueOf(currentTime), jCbRubro.getSelectedItem().toString(), txtObservaciones.getText(), jCbTipoMoneda.getSelectedItem().toString(), 0.00, Double.valueOf(txtMonto.getText()));
            if(planilla.insertar(planilla)){
                JOptionPane.showMessageDialog(null, "Movimiento dado de alta satisfactoriamente");
                this.dispose();
                FrmPlanillaDeControlDiaria.btnActualizar.doClick();
            }
            else{
                JOptionPane.showMessageDialog(null, "Ocurrió un error al agrega movimiento");
                this.dispose();
                FrmPlanillaDeControlDiaria.btnActualizar.doClick();
            }
        }
        
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbMovimiento;
    private javax.swing.JComboBox<String> jCbRubro;
    private javax.swing.JComboBox<String> jCbTipoMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private javax.swing.JTextField txtMonto;
    public javax.swing.JTextField txtNombrepersona;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
