/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.bioscomputacion.Formularios;

import ar.com.bioscomputacion.Funciones.Cliente;
import ar.com.bioscomputacion.Funciones.Productor;
import java.awt.Desktop;
import java.net.URI;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Caco
 */
public class FrmRegistroProductor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmGenerico
     */
    public FrmRegistroProductor() {
        initComponents();
        inicializar();
    }

    public void inicializar(){
        //
        //tfNombre.requestFocus();
    }
    
    /*public void deshabilitarCampos(){
        dateVenta.setEnabled(false);
        txtCliente.setEnabled(false);
        txtDescuento.setEnabled(false);
        btnCancelarVenta.setEnabled(false);
        btnNuevaVenta.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtProducto.setEnabled(false);
        btnSeleccionCliente.setEnabled(false);
        btnAgregarProducto.setEnabled(false);
        btnQuitarProducto.setEnabled(false);
        btnBuscarProducto.setEnabled(false);
        btnPagar.setEnabled(false);
    }
    
    public void habilitarCampos(){
        dateVenta.setEnabled(true);
        txtCliente.setEnabled(true);
        txtDescuento.setEnabled(true);
        btnCancelarVenta.setEnabled(true);
        btnNuevaVenta.setEnabled(false);
        txtCodigo.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtProducto.setEnabled(true);
        btnSeleccionCliente.setEnabled(true);
        btnAgregarProducto.setEnabled(true);
        btnQuitarProducto.setEnabled(true);
        btnBuscarProducto.setEnabled(true);
        btnPagar.setEnabled(true);
    }
    
    public void limpiarCampos(){
        Calendar hoy = new GregorianCalendar();
        dateVenta.setCalendar(hoy);
        
        txtCliente.setText("Consumidor Final");
        txtDescuento.setText("0.00");
        txtCodigo.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("0");
        txtProducto.setText("");
        txtSubTotal.setText("0.00");
        txtTotal.setText("0.00");
        txtImporte.setText("0.00");
        txtCambio.setText("0.00");
        comboMetodoPago.setSelectedIndex(0);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        rdbrRegistrar = new rojeru_san.RSButtonRiple();
        tpProductor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDocumento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbNacionalidad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbEstadoProvincia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbLocalidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfDomicilio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        tfNombreFantasia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfCUIT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfRazonSocial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbCondicionIVA = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tfDomicilioFiscal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        cbPeriodoVentaMiel = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbAñoVentaMiel = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cbMesVentaMiel = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        tfFechaVentaMiel1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfFechaVentaMiel2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfFechaVentaMiel3 = new javax.swing.JTextField();
        rdbrRegistrar1 = new rojeru_san.RSButtonRiple();
        jSeparator6 = new javax.swing.JSeparator();
        rdbrRegistrar2 = new rojeru_san.RSButtonRiple();
        rdbrRegistrar3 = new rojeru_san.RSButtonRiple();
        rdbrRegistrar4 = new rojeru_san.RSButtonRiple();

        setBackground(new java.awt.Color(51, 84, 111));
        setTitle("ALTA DE PRODUCTOR - CAM HONEY BROTHERS");

        rdbrRegistrar.setBackground(new java.awt.Color(47, 110, 164));
        rdbrRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/Iconos/editar.png"))); // NOI18N
        rdbrRegistrar.setText("REGISTRAR PRODUCTOR");
        rdbrRegistrar.setFont(new java.awt.Font("Roboto Bold", 3, 14)); // NOI18N
        rdbrRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbrRegistrarActionPerformed(evt);
            }
        });

        tpProductor.setBackground(new java.awt.Color(51, 84, 111));
        tpProductor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tpProductor.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(51, 84, 111));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("INGRESE LA INFORMACION PERSONAL DEL PRODUCTOR:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE/S Y APELLIDO/S:");

        tfNombre.setBackground(new java.awt.Color(51, 84, 111));
        tfNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("N° DOCUMENTO:");

        tfDocumento.setBackground(new java.awt.Color(51, 84, 111));
        tfDocumento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfDocumento.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NACIONALIDAD:");

        cbNacionalidad.setBackground(new java.awt.Color(36, 33, 33));
        cbNacionalidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbNacionalidad.setForeground(new java.awt.Color(207, 207, 207));
        cbNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cbNacionalidad.setPreferredSize(new java.awt.Dimension(136, 19));
        cbNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNacionalidadActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ESTADO / PROVINCIA:");

        cbEstadoProvincia.setBackground(new java.awt.Color(36, 33, 33));
        cbEstadoProvincia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbEstadoProvincia.setForeground(new java.awt.Color(207, 207, 207));
        cbEstadoProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cbEstadoProvincia.setPreferredSize(new java.awt.Dimension(136, 19));
        cbEstadoProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoProvinciaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LOCALIDAD:");

        cbLocalidad.setBackground(new java.awt.Color(36, 33, 33));
        cbLocalidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbLocalidad.setForeground(new java.awt.Color(207, 207, 207));
        cbLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cbLocalidad.setPreferredSize(new java.awt.Dimension(136, 19));
        cbLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocalidadActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CORREO ELECTRONICO:");

        tfCorreo.setBackground(new java.awt.Color(51, 84, 111));
        tfCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfCorreo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TELEFONO/S:");

        tfTelefono.setBackground(new java.awt.Color(51, 84, 111));
        tfTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfTelefono.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DOMICILIO:");

        tfDomicilio.setBackground(new java.awt.Color(51, 84, 111));
        tfDomicilio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfDomicilio.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDocumento)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbNacionalidad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cbEstadoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbLocalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(335, 335, 335))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCorreo)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tfDomicilio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpProductor.addTab("Informacion personal", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 84, 111));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("INGRESE LOS DATOS DE FACTURACION DEL PRODUCTOR:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOMBRE DE FANTASIA:");

        tfNombreFantasia.setBackground(new java.awt.Color(51, 84, 111));
        tfNombreFantasia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfNombreFantasia.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("N° CUIT:");

        tfCUIT.setBackground(new java.awt.Color(51, 84, 111));
        tfCUIT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfCUIT.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("RAZON SOCIAL:");

        tfRazonSocial.setBackground(new java.awt.Color(51, 84, 111));
        tfRazonSocial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfRazonSocial.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CONDICION FRENTE AL IVA:");
        jLabel15.setToolTipText("");

        cbCondicionIVA.setBackground(new java.awt.Color(36, 33, 33));
        cbCondicionIVA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCondicionIVA.setForeground(new java.awt.Color(207, 207, 207));
        cbCondicionIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "CONSUMIDOR FINAL", "IVA RESP. MONOTRIBUTO", "IVA RESP. INSCRIPTO", "IVA SUJETO EXENTO" }));
        cbCondicionIVA.setPreferredSize(new java.awt.Dimension(136, 19));
        cbCondicionIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCondicionIVAActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DOMICILIO FISCAL:");

        tfDomicilioFiscal.setBackground(new java.awt.Color(51, 84, 111));
        tfDomicilioFiscal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfDomicilioFiscal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addGap(122, 122, 122))
                    .addComponent(tfNombreFantasia)
                    .addComponent(tfRazonSocial)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cbCondicionIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCUIT)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(tfDomicilioFiscal)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNombreFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCondicionIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tfCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDomicilioFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        tpProductor.addTab("Datos de facturacion", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 84, 111));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("CONFIGURE LAS FECHAS DE VENTA DE MIEL:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PERIODO:");

        cbPeriodoVentaMiel.setBackground(new java.awt.Color(36, 33, 33));
        cbPeriodoVentaMiel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbPeriodoVentaMiel.setForeground(new java.awt.Color(207, 207, 207));
        cbPeriodoVentaMiel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1° SEMANA", "2° SEMANA", "3° SEMANA", "4° SEMANA", "1° QUINCENA", "2° QUINCENA" }));
        cbPeriodoVentaMiel.setPreferredSize(new java.awt.Dimension(136, 19));
        cbPeriodoVentaMiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeriodoVentaMielActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("AÑO:");

        cbAñoVentaMiel.setBackground(new java.awt.Color(36, 33, 33));
        cbAñoVentaMiel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbAñoVentaMiel.setForeground(new java.awt.Color(207, 207, 207));
        cbAñoVentaMiel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cbAñoVentaMiel.setPreferredSize(new java.awt.Dimension(136, 19));
        cbAñoVentaMiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAñoVentaMielActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("MES:");

        cbMesVentaMiel.setBackground(new java.awt.Color(36, 33, 33));
        cbMesVentaMiel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbMesVentaMiel.setForeground(new java.awt.Color(207, 207, 207));
        cbMesVentaMiel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cbMesVentaMiel.setPreferredSize(new java.awt.Dimension(136, 19));
        cbMesVentaMiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesVentaMielActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("1ER POSIBLE FECHA DE VENTA:");

        tfFechaVentaMiel1.setBackground(new java.awt.Color(51, 84, 111));
        tfFechaVentaMiel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfFechaVentaMiel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("2DA POSIBLE FECHA DE VENTA:");

        tfFechaVentaMiel2.setBackground(new java.awt.Color(51, 84, 111));
        tfFechaVentaMiel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfFechaVentaMiel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("3ER POSIBLE FECHA DE VENTA:");

        tfFechaVentaMiel3.setBackground(new java.awt.Color(51, 84, 111));
        tfFechaVentaMiel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfFechaVentaMiel3.setForeground(new java.awt.Color(255, 255, 255));

        rdbrRegistrar1.setBackground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar1.setForeground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar1.setText("AGREGAR");
        rdbrRegistrar1.setFont(new java.awt.Font("Roboto Bold", 3, 12)); // NOI18N
        rdbrRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbrRegistrar1ActionPerformed(evt);
            }
        });

        rdbrRegistrar2.setBackground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar2.setForeground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar2.setText("QUITAR");
        rdbrRegistrar2.setFont(new java.awt.Font("Roboto Bold", 3, 12)); // NOI18N
        rdbrRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbrRegistrar2ActionPerformed(evt);
            }
        });

        rdbrRegistrar3.setBackground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar3.setForeground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar3.setText("QUITAR");
        rdbrRegistrar3.setFont(new java.awt.Font("Roboto Bold", 3, 12)); // NOI18N
        rdbrRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbrRegistrar3ActionPerformed(evt);
            }
        });

        rdbrRegistrar4.setBackground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar4.setForeground(new java.awt.Color(0, 0, 0));
        rdbrRegistrar4.setText("QUITAR");
        rdbrRegistrar4.setFont(new java.awt.Font("Roboto Bold", 3, 12)); // NOI18N
        rdbrRegistrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbrRegistrar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(cbPeriodoVentaMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(cbMesVentaMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(cbAñoVentaMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfFechaVentaMiel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                            .addComponent(tfFechaVentaMiel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbrRegistrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdbrRegistrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbrRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFechaVentaMiel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rdbrRegistrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPeriodoVentaMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMesVentaMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAñoVentaMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbrRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfFechaVentaMiel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(29, 29, 29)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(rdbrRegistrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFechaVentaMiel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbrRegistrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFechaVentaMiel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbrRegistrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tpProductor.addTab("Venta de miel", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpProductor)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbrRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tpProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdbrRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tpProductor.getAccessibleContext().setAccessibleName("btrb");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNacionalidadActionPerformed

    private void cbEstadoProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoProvinciaActionPerformed

    private void cbLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLocalidadActionPerformed

    private void rdbrRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbrRegistrarActionPerformed
        
        //Solo es obligatorio el ingreso del nombre del productor
        //los demas datos se controlan para alertar al usuario del sistema que no se han ingresado los mismos
        //pero de todas formas se puede registrar el productor sin dichos datos
        
        Boolean informacionPersonal = (tfDocumento.getText().length() == 0 || tfDomicilio.getText().length() == 0 || tfTelefono.getText().length() == 0 || tfCorreo.getText().length() == 0);
        Boolean datosFacturacion = (tfNombreFantasia.getText().length() == 0 || tfRazonSocial.getText().length() == 0 || String.valueOf(cbCondicionIVA.getSelectedItem()) == "SELECCIONAR" || tfCUIT.getText().length() == 0 || tfDomicilioFiscal.getText().length() == 0);
        Boolean ventaMiel = (tfFechaVentaMiel1.getText().length() == 0 || tfFechaVentaMiel2.getText().length() ==0 || tfFechaVentaMiel3.getText().length() == 0);
               
        //el ingreso del nombre del productor es obligatorio para el registro del mismo
        if (tfNombre.getText().length() == 0){
        
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del productor.", "ALTA DE PRODUCTOR", JOptionPane.ERROR_MESSAGE);
            tfNombre.requestFocus();
            return;
            
        }
        
        //chequea informacion personal, avisa si esta incompleta pero da la opcion de registrar igualmente el productor
        if (informacionPersonal){
        
            if (JOptionPane.showConfirmDialog(null, "La informacion personal del productor se halla incompleta. ¿Desea registrar el productor de todas formas?",
                "REGISTRAR PRODUCTOR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
               //no tengo claro que hacer aca!
                
            }
            else{
                
                tpProductor.setSelectedIndex(0);
                tfDocumento.requestFocus();
                return;
                
            }
                
        }
        
        //chequea datos de facturacion, avisa si estan incompletos pero da la opcion de registrar igualmente el productor
        if (datosFacturacion){
        
            if (JOptionPane.showConfirmDialog(null, "Los datos de facturacion del productor se hallan incompletos. ¿Desea registrar el productor de todas formas?",
                "REGISTRAR PRODUCTOR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
               //no tengo claro que hacer aca!
                
            }
            else{
                
                tpProductor.setSelectedIndex(1);
                tfNombreFantasia.requestFocus();
                return;
                
            }
            
        }
        
        //chequea ventas de miel, avisa si estan incompletas pero da la opcion de registrar igualmente el productor
        if (ventaMiel){
        
            if (JOptionPane.showConfirmDialog(null, "Las fechas de venta de miel del productor no se han configurado completamente. ¿Desea registrar el productor de todas formas?",
                "REGISTRAR PRODUCTOR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
               //no tengo claro que hacer aca!
                
            }
            else{
                
                tpProductor.setSelectedIndex(2);
                cbPeriodoVentaMiel.requestFocus();
                return;
                
            }
            
        }
        
        //se completaron todos los datos y/o se escogio registrar el productor con sus datos y fechas de venta incompletos
        //se registra el productor en la base de datos del sistema
        Productor productor = new Productor(tfFechaVentaMiel1.getText(),tfFechaVentaMiel2.getText(),tfFechaVentaMiel3.getText(),
        tfNombreFantasia.getText(),tfRazonSocial.getText(),"IVA Resp. Inscripto",tfCUIT.getText(),tfDomicilioFiscal.getText(),"Activo",
        tfNombre.getText(),tfDocumento.getText(),"Pais","Estado","Localidad",tfDomicilio.getText(),tfTelefono.getText(),tfCorreo.getText());

        if(productor.registrar(productor)){

            JOptionPane.showMessageDialog(null, "El productor ha sido registrado exitosamente.");
            this.dispose();
            //FrmLogin form = new FrmLogin();
            //form.setVisible(true);

        }
        else{

            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al intentar registrar el productor.");

        }
        
    }//GEN-LAST:event_rdbrRegistrarActionPerformed

    private void cbCondicionIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCondicionIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCondicionIVAActionPerformed

    private void cbPeriodoVentaMielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeriodoVentaMielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPeriodoVentaMielActionPerformed

    private void cbAñoVentaMielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAñoVentaMielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAñoVentaMielActionPerformed

    private void cbMesVentaMielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesVentaMielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesVentaMielActionPerformed

    private void rdbrRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbrRegistrar1ActionPerformed

        //Agrega las fechas de venta a los campos de edicion debajo
        if (String.valueOf(cbPeriodoVentaMiel.getSelectedItem()) == "SELECCIONAR"){
            
            JOptionPane.showMessageDialog(null, "Seleccione un periodo de venta para poder configurar la fecha.");
            rdbrRegistrar.requestFocus();
            
        }
        else{
            
            if (String.valueOf(cbMesVentaMiel.getSelectedItem()) == "SELECCIONAR"){

                JOptionPane.showMessageDialog(null, "Seleccione un mes de venta para poder configurar la fecha.");
                rdbrRegistrar.requestFocus();

            }
            else{
                
                if (String.valueOf(cbAñoVentaMiel.getSelectedItem()) == "SELECCIONAR"){

                    JOptionPane.showMessageDialog(null, "Seleccione un año de venta para poder configurar la fecha.");
                    rdbrRegistrar.requestFocus();

                }
            
                else{
                    
                    if (tfFechaVentaMiel1.getText().length()!=0 && tfFechaVentaMiel2.getText().length()!=0 && tfFechaVentaMiel3.getText().length()!=0){

                        JOptionPane.showMessageDialog(null, "Ya cofiguro las tres fechas de venta del productor.");
                        rdbrRegistrar.requestFocus();

                    }
                    else{
                        
                        if (tfFechaVentaMiel1.getText().length()==0){

                            tfFechaVentaMiel1.setText(cbPeriodoVentaMiel.getSelectedItem()+" "+cbMesVentaMiel.getSelectedItem()+" "+cbAñoVentaMiel.getSelectedItem());
                            rdbrRegistrar.requestFocus();

                        }
                        else{
                            
                            if (tfFechaVentaMiel2.getText().length()==0){

                                tfFechaVentaMiel2.setText(cbPeriodoVentaMiel.getSelectedItem()+" "+cbMesVentaMiel.getSelectedItem()+" "+cbAñoVentaMiel.getSelectedItem());
                                rdbrRegistrar.requestFocus();

                            }
                            else{
                                
                                if (tfFechaVentaMiel3.getText().length()==0){

                                    tfFechaVentaMiel3.setText(cbPeriodoVentaMiel.getSelectedItem()+" "+cbMesVentaMiel.getSelectedItem()+" "+cbAñoVentaMiel.getSelectedItem());
                                    rdbrRegistrar.requestFocus();

                                }
                            
                            }
                            
                        }
                        
                    }
                }
            
            }
        }
        
    }//GEN-LAST:event_rdbrRegistrar1ActionPerformed

    private void rdbrRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbrRegistrar2ActionPerformed

        // Elimina la primer fecha configurada
        tfFechaVentaMiel1.setText("");
        
    }//GEN-LAST:event_rdbrRegistrar2ActionPerformed

    private void rdbrRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbrRegistrar3ActionPerformed

        // Elimina la segunda fecha configurada
        tfFechaVentaMiel2.setText("");
        
    }//GEN-LAST:event_rdbrRegistrar3ActionPerformed

    private void rdbrRegistrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbrRegistrar4ActionPerformed

        // Elimina la tercer fecha configurada
        tfFechaVentaMiel3.setText("");
        
    }//GEN-LAST:event_rdbrRegistrar4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cbAñoVentaMiel;
    public javax.swing.JComboBox<String> cbCondicionIVA;
    public javax.swing.JComboBox<String> cbEstadoProvincia;
    public javax.swing.JComboBox<String> cbLocalidad;
    public javax.swing.JComboBox<String> cbMesVentaMiel;
    public javax.swing.JComboBox<String> cbNacionalidad;
    public javax.swing.JComboBox<String> cbPeriodoVentaMiel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSButtonRiple rdbrRegistrar;
    private rojeru_san.RSButtonRiple rdbrRegistrar1;
    private rojeru_san.RSButtonRiple rdbrRegistrar2;
    private rojeru_san.RSButtonRiple rdbrRegistrar3;
    private rojeru_san.RSButtonRiple rdbrRegistrar4;
    public javax.swing.JTextField tfCUIT;
    public javax.swing.JTextField tfCorreo;
    public javax.swing.JTextField tfDocumento;
    public javax.swing.JTextField tfDomicilio;
    public javax.swing.JTextField tfDomicilioFiscal;
    public javax.swing.JTextField tfFechaVentaMiel1;
    public javax.swing.JTextField tfFechaVentaMiel2;
    public javax.swing.JTextField tfFechaVentaMiel3;
    public javax.swing.JTextField tfNombre;
    public javax.swing.JTextField tfNombreFantasia;
    public javax.swing.JTextField tfRazonSocial;
    public javax.swing.JTextField tfTelefono;
    private javax.swing.JTabbedPane tpProductor;
    // End of variables declaration//GEN-END:variables
}
